### ISSUE TITLE
Simply tutor about build julia script into binary?

### ISSUE THREAD

**Issue by lucasjinreal** [Roger-luo/Brochure.jl#2]
Does there simply tutor for building julia into binary? Something like:

```julia

f(x) = x^2+x
f(4)
```
and then compile it as a single executable file?
More complicated, compile as binary when use third party package?

**Comment by Roger-luo** [comment]
Yes, check PackageCompiler.jl it provides a AOT compiler for Julia scripts. But notice we currently can not build a standalone binary (which means something completely without runtime) although in principle we can but it lacks of people working on it.

**Comment by Roger-luo** [comment]
https://github.com/JuliaLang/PackageCompiler.jl

I'll add some more demo project to help people understand how to write a practical project with Julia later. But I don't have plans on building binaries, since just using it is simple, but explain how these things works would be more advanced.

**Comment by Roger-luo** [comment]
And Julia is a JIT language, which means f(4) in your example compiles to binary instructions in the memory rather than a binary file. If you want to make real binary files, it's another story. The PackageCompiler README explains how already I think.

**Comment by lucasjinreal** [comment]
@Roger-luo  compiling Julia scripts help people distribute or deploy their projects. this is really dynamic languages lack of, especially python. (you may got a lots of dedencies trouble when deploying a python project on your server, but with a single executable file life goes much more easy.)

**Comment by lucasjinreal** [comment]
Just wonder how Julians think and do about this.

**Comment by Roger-luo** [comment]
Yes, I understand a standalone binary is necessary for production. Julia can be compiled to one binary, if you don't care about the quality for now. It's just there are things with higher priority tasks (like improve JIT latency, compiler optimization) than making a nice standalone binary. Since most people use Julia on clusters instead of small devices, thus a large working binary should be sufficient for now.

**Comment by Roger-luo** [comment]
And yes, since many dynamic language can not specified the generic code efficiently, the compilation sometimes is pretty bad. This not a problem for Julia, Julia can make shared libraries. The current problem is mainly about making small, standalone binaries, you won't want to distribute hello world with a blas compiled in it. But if you just want binary and do not care about the size, Julia can even be compiled to C callable shared libraries, the current functionality should be sufficient.

And I would suggest to join open source contribution, if there's some features you want and doable since the community is young and always lack of people working on things.

**Comment by lucasjinreal** [comment]
@Roger-luo thanks for your clarification. I will keep dig into Julia

**Comment by Roger-luo** [comment]
这个issue应该已经解决了。
